enum OrderType {
  Sell
  Buy
}

enum OrderStatus {
  Active
  Closed
  Canceled
}

type User {
  id: ID!
  active: Int!
  closed: Int!
  canceled: Int!
  timestamp: String!
  # feesPaid: BigInt!
}

type OpenOrderEvent {
  id: ID!
  market: String! @index
  user: String! @index
  orderId: String! @index
  baseAmount: BigInt!
  quoteAmount: BigInt!
  asset: String!
  amount: BigInt!
  orderType: OrderType!
  price: BigInt!
  timestamp: String!
  txId: String! @index
}

type Order {
  id: ID!
  market: String! @index
  asset: String! @index
  amount: BigInt!
  orderType: OrderType! @index
  price: BigInt! @index
  user: String! @index
  status: OrderStatus! @index
  initialAmount: BigInt!
  timestamp: String!
}

type ActiveSellOrder {
  id: ID!
  market: String! @index
  asset: String! @index
  amount: BigInt!
  orderType: OrderType! @index
  price: BigInt! @index
  user: String! @index
  status: OrderStatus! @index
  initialAmount: BigInt!
  timestamp: String!
}

type ActiveBuyOrder {
  id: ID!
  market: String! @index
  asset: String! @index
  amount: BigInt!
  orderType: OrderType! @index
  price: BigInt! @index
  user: String! @index
  status: OrderStatus! @index
  initialAmount: BigInt!
  timestamp: String!
}

type CancelOrderEvent {
  id: ID!
  market: String! @index
  user: String! @index
  orderId: String! @index
  baseAmount: BigInt!
  quoteAmount: BigInt!
  timestamp: String!
  txId: String! @index
}

type TradeOrderEvent {
  id: ID!
  market: String! @index
  sellOrderId: String! @index
  buyOrderId: String! @index
  tradeSize: BigInt! @index
  tradePrice: BigInt! @index
  seller: String! @index
  buyer: String! @index
  maker: String! @index
  taker: String! @index
  sellerIsMaker: Boolean! @index
  sellerBaseAmount: BigInt!
  sellerQuoteAmount: BigInt!
  buyerBaseAmount: BigInt!
  buyerQuoteAmount: BigInt!
  timestamp: String!
  txId: String! @index
}

type TraderValue {
  id: ID!
  trader: String! @index
  market: String! @index
  value: Float!
  feesPaid: Float!
}

type DepositEvent {
  id: ID!
  market: String! @index
  user: String! @index
  amount: BigInt!
  asset: String! @index
  baseAmount: BigInt!
  quoteAmount: BigInt!
  timestamp: String!
  txId: String! @index
}
type WithdrawEvent {
  id: ID!
  market: String! @index
  user: String! @index
  amount: BigInt!
  asset: String! @index
  baseAmount: BigInt!
  quoteAmount: BigInt! 
  timestamp: String!
  txId: String! @index
}

type WithdrawToMarketEvent {
  id: ID!
  market: String! @index
  toMarket: String! @index
  user: String! @index
  amount: BigInt!
  asset: String! @index
  baseAmount: BigInt!
  quoteAmount: BigInt! 
  timestamp: String!
  txId: String! @index
}

type SetEpochEvent {
  id: ID!
  market: String! @index
  epoch: BigInt!
  epochDuration: BigInt!
  timestamp: String!
  txId: String! @index
}

type SetMatcherRewardEvent {
  id: ID!
  market: String! @index
  amount: BigInt!
  timestamp: String!
  txId: String! @index
}

type SetStoreOrderChangeInfoEvent {
  id: ID!
  market: String! @index
  store: Boolean!
  timestamp: String!
  txId: String! @index
}

type SetMinOrderSizeEvent {
  id: ID!
  market: String! @index
  size: BigInt!
  timestamp: String!
  txId: String! @index
}

type SetMinOrderPriceEvent {
  id: ID!
  market: String! @index
  price: BigInt!
  timestamp: String!
  txId: String! @index
}

type ProtocolFee @entity {
    id: ID!    
    # market: String! @index 
    makerFee: BigInt!
    takerFee: BigInt!
    volumeThreshold: BigInt! 
    eventId: String!
    timestamp: String!  

}

type SetProtocolFeeEvent @entity {
    id: ID!               
    market: String! @index
    timestamp: String!  
    txId: String! @index
}